### ISSUE TITLE
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by IvanGarcia7** [nv-tlabs/datasetGAN_release#6]
When i try to reproduce the example execution (step number 1 and 2) appear the following message ->CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`.

I execute the scrips in my RTX 3080 graphic card. How can I solve it? I tried the example car_20

**Comment by IvanGarcia7** [comment]
After debugging the code, the line that generates this error is the following:

**Comment by IvanGarcia7** [comment]
Changing the Cuda and torch version appear the following error:

Traceback (most recent call last):
  File "train_interpreter.py", line 589, in <module>
    generate_data(opts, args.resume, args.num_sample, vis=args.save_vis, start_step=args.start_step)
  File "train_interpreter.py", line 265, in generate_data
    return_upsampled_layers=True)
  File "../utils/utils.py", line 76, in latent_to_image
    img_list, affine_layers = g_all.module.g_synthesis(style_latents)
  File "/mnt/hdda/Data/envs/dataGan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "../models/stylegan1.py", line 557, in forward
    x, x2 = m(x, dlatents_in[:, 2 * i:2 * i + 2])
  File "/mnt/hdda/Data/envs/dataGan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "../models/stylegan1.py", line 391, in forward
    x = self.conv0_up(x)
  File "/mnt/hdda/Data/envs/dataGan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "../models/stylegan1.py", line 105, in forward
    x = F.conv_transpose2d(x, w, stride=2, padding=(w.size(-1) - 1) // 2)
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

**Comment by IvanGarcia7** [comment]
The error was due to an incompatibility between the version of Cuda and pytorch. After setting the appropriate versions the error disappears
